<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>physical-conditions – Constant Potential MD in LAMMPS</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ff0631ae66c640f7beec88805fcb678e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Constant Potential MD in LAMMPS</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./01-fundamentals.html"> 
<span class="menu-text">1. Fundamentals</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./02-force-fields.html"> 
<span class="menu-text">2. Force Fields</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./03-physical-conditions.html" aria-current="page"> 
<span class="menu-text">3. Physical Conditions</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./04-electrostatics.html"> 
<span class="menu-text">4. Electrostatics</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./05-electrodes-cpm.html"> 
<span class="menu-text">5. Electrodes &amp; CPM</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./06-electrode-package.html"> 
<span class="menu-text">6. ELECTRODE Package</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./07-example-simulation.html"> 
<span class="menu-text">7. Example</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./08-troubleshooting.html"> 
<span class="menu-text">8. Troubleshooting</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./references.html"> 
<span class="menu-text">References</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/lammps/lammps"> <i class="bi bi-github" role="img" aria-label="LAMMPS GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sec-physical-conditions" id="toc-sec-physical-conditions" class="nav-link active" data-scroll-target="#sec-physical-conditions">Physical Conditions</a>
  <ul class="collapse">
  <li><a href="#what-is-being-held-constant" id="toc-what-is-being-held-constant" class="nav-link" data-scroll-target="#what-is-being-held-constant">What Is Being Held Constant?</a></li>
  <li><a href="#the-physical-meaning-of-temperature" id="toc-the-physical-meaning-of-temperature" class="nav-link" data-scroll-target="#the-physical-meaning-of-temperature">The Physical Meaning of Temperature</a>
  <ul class="collapse">
  <li><a href="#temperature-is-a-statistical-property" id="toc-temperature-is-a-statistical-property" class="nav-link" data-scroll-target="#temperature-is-a-statistical-property">Temperature Is a Statistical Property</a></li>
  <li><a href="#temperature-vs.-kinetic-energy" id="toc-temperature-vs.-kinetic-energy" class="nav-link" data-scroll-target="#temperature-vs.-kinetic-energy">Temperature vs.&nbsp;Kinetic Energy</a></li>
  </ul></li>
  <li><a href="#time-integration-and-timestep" id="toc-time-integration-and-timestep" class="nav-link" data-scroll-target="#time-integration-and-timestep">Time Integration and Timestep</a>
  <ul class="collapse">
  <li><a href="#the-velocity-verlet-algorithm" id="toc-the-velocity-verlet-algorithm" class="nav-link" data-scroll-target="#the-velocity-verlet-algorithm">The Velocity Verlet Algorithm</a></li>
  <li><a href="#why-velocity-verlet" id="toc-why-velocity-verlet" class="nav-link" data-scroll-target="#why-velocity-verlet">Why Velocity Verlet?</a></li>
  <li><a href="#timestep-selection" id="toc-timestep-selection" class="nav-link" data-scroll-target="#timestep-selection">Timestep Selection</a></li>
  <li><a href="#bond-constraints" id="toc-bond-constraints" class="nav-link" data-scroll-target="#bond-constraints">Bond Constraints</a></li>
  </ul></li>
  <li><a href="#thermostats-controlling-temperature" id="toc-thermostats-controlling-temperature" class="nav-link" data-scroll-target="#thermostats-controlling-temperature">Thermostats — Controlling Temperature</a>
  <ul class="collapse">
  <li><a href="#why-we-need-thermostats" id="toc-why-we-need-thermostats" class="nav-link" data-scroll-target="#why-we-need-thermostats">Why We Need Thermostats</a></li>
  <li><a href="#thermostat-algorithms" id="toc-thermostat-algorithms" class="nav-link" data-scroll-target="#thermostat-algorithms">Thermostat Algorithms</a></li>
  <li><a href="#what-temperature-actually-controls" id="toc-what-temperature-actually-controls" class="nav-link" data-scroll-target="#what-temperature-actually-controls">What Temperature Actually Controls</a></li>
  </ul></li>
  <li><a href="#barostats-controlling-pressure" id="toc-barostats-controlling-pressure" class="nav-link" data-scroll-target="#barostats-controlling-pressure">Barostats — Controlling Pressure</a>
  <ul class="collapse">
  <li><a href="#pressure-in-md" id="toc-pressure-in-md" class="nav-link" data-scroll-target="#pressure-in-md">Pressure in MD</a></li>
  <li><a href="#barostat-types" id="toc-barostat-types" class="nav-link" data-scroll-target="#barostat-types">Barostat Types</a></li>
  <li><a href="#what-pressure-controls-physically" id="toc-what-pressure-controls-physically" class="nav-link" data-scroll-target="#what-pressure-controls-physically">What Pressure Controls Physically</a></li>
  </ul></li>
  <li><a href="#integrators-in-lammps" id="toc-integrators-in-lammps" class="nav-link" data-scroll-target="#integrators-in-lammps">Integrators in LAMMPS</a>
  <ul class="collapse">
  <li><a href="#combining-thermostats-and-barostats" id="toc-combining-thermostats-and-barostats" class="nav-link" data-scroll-target="#combining-thermostats-and-barostats">Combining Thermostats and Barostats</a></li>
  <li><a href="#for-electrode-simulations" id="toc-for-electrode-simulations" class="nav-link" data-scroll-target="#for-electrode-simulations">For ELECTRODE Simulations</a></li>
  </ul></li>
  <li><a href="#observables-what-you-actually-measure" id="toc-observables-what-you-actually-measure" class="nav-link" data-scroll-target="#observables-what-you-actually-measure">Observables — What You Actually Measure</a>
  <ul class="collapse">
  <li><a href="#thermodynamic-output" id="toc-thermodynamic-output" class="nav-link" data-scroll-target="#thermodynamic-output">Thermodynamic Output</a></li>
  <li><a href="#computes-for-analysis" id="toc-computes-for-analysis" class="nav-link" data-scroll-target="#computes-for-analysis">Computes for Analysis</a></li>
  <li><a href="#fix-specific-output-electrode" id="toc-fix-specific-output-electrode" class="nav-link" data-scroll-target="#fix-specific-output-electrode">Fix-Specific Output (ELECTRODE)</a></li>
  <li><a href="#trajectory-output" id="toc-trajectory-output" class="nav-link" data-scroll-target="#trajectory-output">Trajectory Output</a></li>
  </ul></li>
  <li><a href="#physical-conditions-output-summary" id="toc-physical-conditions-output-summary" class="nav-link" data-scroll-target="#physical-conditions-output-summary">Physical Conditions → Output Summary</a></li>
  <li><a href="#common-mistakes" id="toc-common-mistakes" class="nav-link" data-scroll-target="#common-mistakes">Common Mistakes</a></li>
  <li><a href="#next-steps" id="toc-next-steps" class="nav-link" data-scroll-target="#next-steps">Next Steps</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="sec-physical-conditions" class="level1">
<h1>Physical Conditions</h1>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>In this section
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>What NVE, NVT, NPT mean physically and when to use each</li>
<li>How thermostats work (algorithms, LAMMPS syntax, physical meaning)</li>
<li>How barostats control pressure and volume</li>
<li>Timestep selection and why it matters</li>
<li>What observables you can measure and what they tell you</li>
</ul>
</div>
</div>
<section id="what-is-being-held-constant" class="level2">
<h2 class="anchored" data-anchor-id="what-is-being-held-constant">What Is Being Held Constant?</h2>
<p>Real experiments control temperature, pressure, and composition. In MD, we choose which of these to hold fixed — this determines the <strong>statistical ensemble</strong> and thus which thermodynamic properties we can legitimately compute.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 17%">
<col style="width: 22%">
<col style="width: 28%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Ensemble</th>
<th>LAMMPS Fix</th>
<th>What’s Fixed</th>
<th>What Fluctuates</th>
<th>Use Case</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>NVE</td>
<td><code>fix nve</code></td>
<td>E, V, N</td>
<td>T, P</td>
<td>Microcanonical; equilibrium check</td>
</tr>
<tr class="even">
<td>NVT</td>
<td><code>fix nvt</code> or <code>fix npt</code></td>
<td>T, V, N</td>
<td>E, P</td>
<td>Canonical; most production</td>
</tr>
<tr class="odd">
<td>NPT</td>
<td><code>fix npt</code></td>
<td>T, P, N</td>
<td>E, V</td>
<td>Isobaric; density-sensitive properties</td>
</tr>
<tr class="even">
<td>NPH</td>
<td><code>fix nph</code></td>
<td>P, H, N</td>
<td>T, V</td>
<td>Isobaric without thermostat (rare)</td>
</tr>
</tbody>
</table>
<p>The ensemble choice is not just convention — it determines which statistical mechanics formula you must use to connect simulation results to experimental observables.</p>
<p><strong>Example</strong>: If you run NVT and compute the compressibility, you need to use the NVT formula for fluctuations, not the NPT formula. Using the wrong ensemble = wrong physics.</p>
</section>
<section id="the-physical-meaning-of-temperature" class="level2">
<h2 class="anchored" data-anchor-id="the-physical-meaning-of-temperature">The Physical Meaning of Temperature</h2>
<section id="temperature-is-a-statistical-property" class="level3">
<h3 class="anchored" data-anchor-id="temperature-is-a-statistical-property">Temperature Is a Statistical Property</h3>
<p>In MD, temperature is defined from kinetic energy:</p>
<p><span class="math display">\[T = \frac{2}{3N_f k_B} \sum_i \frac{1}{2}m_i v_i^2\]</span></p>
<p>Where <span class="math inline">\(N_f\)</span> is the number of degrees of freedom (3N minus constraints).</p>
<p><strong>Key points</strong>: - Temperature is a <strong>mean quantity</strong> — the instantaneous value fluctuates - Fluctuations scale as <span class="math inline">\(1/\sqrt{N}\)</span> — larger systems have smaller relative fluctuations - For N=1000 water molecules, T fluctuates by about ±10 K even in equilibrium</p>
</section>
<section id="temperature-vs.-kinetic-energy" class="level3">
<h3 class="anchored" data-anchor-id="temperature-vs.-kinetic-energy">Temperature vs.&nbsp;Kinetic Energy</h3>
<p>For an ideal gas, <span class="math inline">\(T\)</span> is directly proportional to kinetic energy. But in a real system:</p>
<p><span class="math display">\[T \propto \langle KE \rangle / N_f\]</span></p>
<p>This means: - If you increase the timestep and integration becomes inaccurate, KE may “drift” - If atoms are constrained (shake), those degrees of freedom don’t contribute to T - A frozen atom (velocity set to zero) doesn’t contribute to temperature at all</p>
<p><strong>Why this matters</strong>: <code>compute temp</code> uses the actual velocities of atoms in the group. If you thermostat only a subgroup, only those atoms’ velocities contribute to that compute.</p>
</section>
</section>
<section id="time-integration-and-timestep" class="level2">
<h2 class="anchored" data-anchor-id="time-integration-and-timestep">Time Integration and Timestep</h2>
<section id="the-velocity-verlet-algorithm" class="level3">
<h3 class="anchored" data-anchor-id="the-velocity-verlet-algorithm">The Velocity Verlet Algorithm</h3>
<p>MD integrates Newton’s equations numerically. The velocity Verlet algorithm is:</p>
<ol type="1">
<li><strong>Half-step velocity</strong>: <span class="math inline">\(v(t + \Delta t/2) = v(t) + 0.5 \cdot F(t)/m \cdot \Delta t\)</span></li>
<li><strong>Full-step position</strong>: <span class="math inline">\(x(t + \Delta t) = x(t) + v(t + \Delta t/2) \cdot \Delta t\)</span></li>
<li><strong>Compute new forces</strong>: <span class="math inline">\(F(t + \Delta t) = -\nabla U(x(t + \Delta t))\)</span></li>
<li><strong>Complete velocity</strong>: <span class="math inline">\(v(t + \Delta t) = v(t + \Delta t/2) + 0.5 \cdot F(t + \Delta t)/m \cdot \Delta t\)</span></li>
</ol>
<p><strong>Why this order?</strong> Because <span class="math inline">\(F(t + \Delta t)\)</span> depends on <span class="math inline">\(x(t + \Delta t)\)</span>, which is only known after step 2.</p>
</section>
<section id="why-velocity-verlet" class="level3">
<h3 class="anchored" data-anchor-id="why-velocity-verlet">Why Velocity Verlet?</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 41%">
<col style="width: 58%">
</colgroup>
<thead>
<tr class="header">
<th>Property</th>
<th>Significance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Time-reversible</td>
<td>Symplectic integrator; conserves phase space structure</td>
</tr>
<tr class="even">
<td>Stable</td>
<td>Energy drift is bounded over long simulations</td>
</tr>
<tr class="odd">
<td>Velocity explicit</td>
<td>Velocities are computed at full timestep (unlike position Verlet)</td>
</tr>
</tbody>
</table>
</section>
<section id="timestep-selection" class="level3">
<h3 class="anchored" data-anchor-id="timestep-selection">Timestep Selection</h3>
<p>The timestep <span class="math inline">\(\Delta t\)</span> must be small enough to resolve the fastest motion in the system:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Motion</th>
<th>Characteristic Frequency</th>
<th>Period</th>
<th>Δt Limit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>C-H bond stretch</td>
<td>~3000 cm⁻¹</td>
<td>~11 fs</td>
<td>~0.5 fs</td>
</tr>
<tr class="even">
<td>O-H bond stretch</td>
<td>~3500 cm⁻¹</td>
<td>~9.5 fs</td>
<td>~0.5 fs</td>
</tr>
<tr class="odd">
<td>H-O-H bend</td>
<td>~1600 cm⁻¹</td>
<td>~21 fs</td>
<td>~1 fs</td>
</tr>
<tr class="even">
<td>LJ repulsion</td>
<td>Very fast</td>
<td>~2–4 fs</td>
<td>~0.5 fs</td>
</tr>
<tr class="odd">
<td>Metal phonon</td>
<td>~5–10 ps period</td>
<td>ps scale</td>
<td>~1–2 fs</td>
</tr>
</tbody>
</table>
<p><strong>Typical values</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>System</th>
<th>Timestep</th>
<th>Reason</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Flexible molecules (methanol)</td>
<td>0.5 fs</td>
<td>Fast C-H stretch</td>
</tr>
<tr class="even">
<td>SPC/E water (rigid)</td>
<td>1 fs</td>
<td>Fast O-H is constrained</td>
</tr>
<tr class="odd">
<td>TIP4P water (rigid)</td>
<td>1–2 fs</td>
<td>Fast O-H is constrained</td>
</tr>
<tr class="even">
<td>Metal (Ag, Au)</td>
<td>2 fs</td>
<td>Heavy atoms; slow phonons</td>
</tr>
<tr class="odd">
<td>with <code>fix shake</code></td>
<td>2 fs</td>
<td>Constrains remove fast modes</td>
</tr>
</tbody>
</table>
<p><strong>How to check if timestep is too large</strong>:</p>
<pre class="lammps"><code># Run NVE and check energy drift
fix conservative all nve
run 10000    # 10 ps at 1 fs
# In output, check TotEng drift
# If TotEng changes by &gt;0.1%, reduce timestep</code></pre>
</section>
<section id="bond-constraints" class="level3">
<h3 class="anchored" data-anchor-id="bond-constraints">Bond Constraints</h3>
<p><code>fix shake</code> removes fast degrees of freedom by constraint:</p>
<pre class="lammps"><code>fix constrain all shake 1e-4 200 0 a 1.0 b 1.0</code></pre>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Parameter</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>1e-4</code></td>
<td>Tolerance for constraint satisfaction</td>
</tr>
<tr class="even">
<td><code>200</code></td>
<td>Maximum iterations per step</td>
</tr>
<tr class="odd">
<td><code>0</code></td>
<td>Which atoms to NOT constrain (none)</td>
</tr>
<tr class="even">
<td><code>a 1.0</code></td>
<td>Bond type 1 has length 1.0 Å</td>
</tr>
<tr class="odd">
<td><code>b 1.0</code></td>
<td>Bond type 2 has length 1.0 Å</td>
</tr>
</tbody>
</table>
<p><strong>Physical effect</strong>: Instead of integrating the fast O-H stretch (period ~9.5 fs), it’s held fixed. This removes the mode requiring small Δt.</p>
<p><strong>Result</strong>: Can use Δt = 2 fs (2× faster simulation) with same accuracy for slower modes.</p>
</section>
</section>
<section id="thermostats-controlling-temperature" class="level2">
<h2 class="anchored" data-anchor-id="thermostats-controlling-temperature">Thermostats — Controlling Temperature</h2>
<section id="why-we-need-thermostats" class="level3">
<h3 class="anchored" data-anchor-id="why-we-need-thermostats">Why We Need Thermostats</h3>
<p>NVE (microcanonical) samples an ensemble where total energy is conserved. But: - Initial velocities are drawn from a Maxwell-Boltzmann distribution at temperature T - As simulation proceeds, numerical errors slightly change total energy - The system doesn’t perfectly sample canonical (NVT) — it’s a quasi-ensemble</p>
<p><strong>For production</strong>, we want true canonical ensemble sampling → use a thermostat.</p>
</section>
<section id="thermostat-algorithms" class="level3">
<h3 class="anchored" data-anchor-id="thermostat-algorithms">Thermostat Algorithms</h3>
<section id="velocity-rescaling-fix-temprescale" class="level4">
<h4 class="anchored" data-anchor-id="velocity-rescaling-fix-temprescale">Velocity Rescaling (<code>fix temp/rescale</code>)</h4>
<pre class="lammps"><code>fix tempctr all temp/rescale 10 300.0 300.0 0.02 1.0</code></pre>
<p>Simple scaling: multiply all velocities by a factor to match target T:</p>
<p><span class="math display">\[v_{new} = v_{old} \sqrt{\frac{T_{target}}{T_{current}}}\]</span></p>
<p><strong>Problems</strong>: - Does not produce correct fluctuations (variance too low) - Not physically motivated (invented for MD) - Can distort dynamics if coupling too tight</p>
<p><strong>Use only for</strong>: quick equilibration before switching to a proper thermostat.</p>
</section>
<section id="berendsen-thermostat-fix-berendsen" class="level4">
<h4 class="anchored" data-anchor-id="berendsen-thermostat-fix-berendsen">Berendsen Thermostat (<code>fix berendsen</code>)</h4>
<pre class="lammps"><code>fix ber all berendsen temp 300.0 300.0 100.0</code></pre>
<p>Weak coupling to heat bath:</p>
<p><span class="math display">\[\frac{dT}{dt} = \frac{T_{bath} - T}{\tau}\]</span></p>
<p><strong>Problems</strong>: - Produces temperature fluctuations that are too small by factor <span class="math inline">\(\sqrt{2/N_f}\)</span> - Does not sample canonical ensemble correctly - Not recommended for production</p>
<p><strong>Advantage</strong>: very stable; good for systems that are hard to equilibrate.</p>
</section>
<section id="nosé-hoover-thermostat-fix-nvt" class="level4">
<h4 class="anchored" data-anchor-id="nosé-hoover-thermostat-fix-nvt">Nosé-Hoover Thermostat (<code>fix nvt</code>)</h4>
<pre class="lammps"><code>fix nvt_all all nvt temp 300.0 300.0 100.0</code></pre>
<p><strong>Extended system method</strong>: adds a degree of freedom <span class="math inline">\(s\)</span> (the “thermostat”) that shares energy with the system.</p>
<p>The modified Hamiltonian:</p>
<p><span class="math display">\[H' = \sum \frac{p_i^2}{2m_i} + U(\mathbf{r}) + \frac{Q}{2}\dot{s}^2 + (N_f+1)k_B T \ln s\]</span></p>
<p>Where <span class="math inline">\(Q\)</span> is the ” thermostat mass” (related to <code>tdamp</code> in LAMMPS).</p>
<p><strong>How it works</strong>: - If system is too hot → thermostat absorbs energy (s accelerates) - If system is too cold → thermostat gives energy (s decelerates) - Over time, correct canonical distribution is sampled</p>
<p><strong>Parameters</strong>: - <code>300.0 300.0</code> = target temperature and damping source temperature (both same in NVT) - <code>100.0</code> = <code>tdamp</code> = coupling time in fs (should be ~100 fs for correct fluctuations)</p>
<p><strong>Why 100 fs?</strong> The characteristic time for energy exchange between degrees of freedom is ~100 fs. Too small = over-damped; too large = slow equipartition.</p>
</section>
<section id="langevin-thermostat-fix-langevin" class="level4">
<h4 class="anchored" data-anchor-id="langevin-thermostat-fix-langevin">Langevin Thermostat (<code>fix langevin</code>)</h4>
<pre class="lammps"><code>fix mylang all langevin 300.0 300.0 100.0 12345</code></pre>
<p><strong>Stochastic differential equation</strong>:</p>
<p><span class="math display">\[m\frac{dv}{dt} = F - \gamma mv + \sqrt{2\gamma m k_B T} \, \xi(t)\]</span></p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 76%">
</colgroup>
<thead>
<tr class="header">
<th>Term</th>
<th>Physical Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(F\)</span></td>
<td>Conservative force from potential</td>
</tr>
<tr class="even">
<td><span class="math inline">\(-\gamma mv\)</span></td>
<td>Friction (damping)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\sqrt{2\gamma m k_B T} \, \xi(t)\)</span></td>
<td>Random noise; <span class="math inline">\(\xi(t)\)</span> is Gaussian white noise</td>
</tr>
</tbody>
</table>
<p><strong>Physical interpretation</strong>: the system is coupled to a heat bath that: 1. Applies friction (energy dissipation) 2. Supplies random impulses (thermal fluctuations)</p>
<p>Together, these produce correct canonical sampling (fluctuation-dissipation theorem).</p>
<p><strong>Parameters</strong>: - <code>300.0 300.0</code> = target temperature, temperature of heat bath - <code>100.0</code> = damping time <span class="math inline">\(\tau_{damp} = m/\gamma\)</span> - <code>12345</code> = random seed (set explicitly for reproducibility)</p>
<p><strong>Advantages</strong>: - Ergodic even for small systems (stochastic component) - Good for non-equilibrium dynamics (shear, external field) - Good for systems with heterogeneous dynamics (some atoms much heavier than others)</p>
<p><strong>Disadvantages</strong>: - Adds artificial friction; modifies dynamics (no “true” Newtonian trajectory) - Inertial effects from friction alter short-time behavior</p>
</section>
<section id="thermostat-comparison" class="level4">
<h4 class="anchored" data-anchor-id="thermostat-comparison">Thermostat Comparison</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 29%">
<col style="width: 14%">
<col style="width: 25%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Thermostat</th>
<th>Fluctuations Correct?</th>
<th>Ergodicity</th>
<th>Affects Dynamics?</th>
<th>Best Use</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>temp/rescale</td>
<td>❌ No (all same T)</td>
<td>N/A</td>
<td>Yes (artificial)</td>
<td>Quick equilibration only</td>
</tr>
<tr class="even">
<td>berendsen</td>
<td>❌ No (too small)</td>
<td>Poor</td>
<td>Weakly</td>
<td>Not recommended</td>
</tr>
<tr class="odd">
<td>nvt (Nosé-Hoover)</td>
<td>✅ Yes</td>
<td>Good</td>
<td>Weakly</td>
<td>Standard production</td>
</tr>
<tr class="even">
<td>langevin</td>
<td>✅ Yes</td>
<td>Good (stochastic)</td>
<td>Yes (friction)</td>
<td>Non-equilibrium; heterogeneous</td>
</tr>
<tr class="odd">
<td>npt (with T-chain)</td>
<td>✅ Yes</td>
<td>Best</td>
<td>Weakly</td>
<td>Difficult cases</td>
</tr>
</tbody>
</table>
<p><strong>For ELECTRODE simulations</strong>: Langevin on electrolyte is common because it ensures ergodicity even with constrained electrodes.</p>
</section>
</section>
<section id="what-temperature-actually-controls" class="level3">
<h3 class="anchored" data-anchor-id="what-temperature-actually-controls">What Temperature Actually Controls</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 34%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>T Change</th>
<th>Physical Effect</th>
<th>Observable</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Increase T</td>
<td>Higher kinetic energy → faster motion</td>
<td>Higher diffusion coefficient</td>
</tr>
<tr class="even">
<td>T too high</td>
<td>Bonds may break; chemical reactions</td>
<td>System decomposes</td>
</tr>
<tr class="odd">
<td>T too low</td>
<td>Slow dynamics; metastable states</td>
<td>Long equilibration times</td>
</tr>
<tr class="even">
<td>T fluctuations too small</td>
<td>Wrong ensemble (Berendsen)</td>
<td>Wrong heat capacity</td>
</tr>
</tbody>
</table>
<p><strong>The diffusion coefficient</strong> <span class="math inline">\(D\)</span> depends on temperature:</p>
<p><span class="math display">\[D(T) \approx D_0 \exp\left(-\frac{E_a}{k_B T}\right)\]</span></p>
<p>For water, <span class="math inline">\(E_a\)</span> ≈ 0.2 eV, so doubling T roughly doubles D.</p>
</section>
</section>
<section id="barostats-controlling-pressure" class="level2">
<h2 class="anchored" data-anchor-id="barostats-controlling-pressure">Barostats — Controlling Pressure</h2>
<section id="pressure-in-md" class="level3">
<h3 class="anchored" data-anchor-id="pressure-in-md">Pressure in MD</h3>
<p>Pressure from virial theorem:</p>
<p><span class="math display">\[P = \frac{Nk_BT}{V} + \frac{1}{3V}\left\langle \sum_i \mathbf{r}_i \cdot \mathbf{F}_i \right\rangle\]</span></p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 76%">
</colgroup>
<thead>
<tr class="header">
<th>Term</th>
<th>Physical Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(Nk_BT/V\)</span></td>
<td>Kinetic contribution (ideal gas pressure)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\langle \sum \mathbf{r} \cdot \mathbf{F} \rangle / 3V\)</span></td>
<td>Virial from interatomic forces</td>
</tr>
</tbody>
</table>
<p><strong>For isotropic bulk</strong>: this scalar P is appropriate.</p>
<p><strong>For anisotropic systems</strong> (slabs, interfaces): we have a <strong>pressure tensor</strong>:</p>
<p><span class="math display">\[P_{\alpha\beta} = \frac{Nk_BT}{V}\delta_{\alpha\beta} + \frac{1}{V}\left\langle \sum_i r_{i\alpha} F_{i\beta} \right\rangle\]</span></p>
<p>Where <span class="math inline">\(\alpha, \beta \in \{x, y, z\}\)</span>.</p>
</section>
<section id="barostat-types" class="level3">
<h3 class="anchored" data-anchor-id="barostat-types">Barostat Types</h3>
<section id="nose-hoover-barostat-fix-npt" class="level4">
<h4 class="anchored" data-anchor-id="nose-hoover-barostat-fix-npt">Nose-Hoover Barostat (<code>fix npt</code>)</h4>
<pre class="lammps"><code>fix npt_all all npt temp 300.0 300.0 100.0 iso 1.0 1.0 500.0</code></pre>
<p><strong>Keywords for pressure coupling</strong>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 47%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>Keyword</th>
<th>What It Controls</th>
<th>Use When</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>iso</code></td>
<td>All three components equally</td>
<td>Isotropic bulk liquid</td>
</tr>
<tr class="even">
<td><code>aniso</code></td>
<td>x, y, z independently</td>
<td>Anisotropic crystals; allow volume changes in each direction</td>
</tr>
<tr class="odd">
<td><code>semiiso</code></td>
<td>xy coupled, z separate</td>
<td>Slab geometry with non-periodic z</td>
</tr>
</tbody>
</table>
<p>For <strong>slab geometries</strong> (electrode-electrolyte):</p>
<pre class="lammps"><code>fix npt_slab all npt temp 300.0 300.0 100.0 semiiso 1.0 1.0 500.0</code></pre>
<p>This controls P_x = P_y (the periodic directions), but allows P_z to be different (the non-periodic direction). The volume adjusts to satisfy the x,y pressure constraint.</p>
<p><strong>Why semiiso?</strong> In slab geometry with non-periodic z: - x and y are periodic → pressure in those directions makes sense - z has vacuum/fixed boundaries → the pressure tensor component is less meaningful - Allowing P_z to float lets the system find its natural spacing</p>
</section>
<section id="mtk-barostat-martyna-tobias-klein" class="level4">
<h4 class="anchored" data-anchor-id="mtk-barostat-martyna-tobias-klein">MTK Barostat (Martyna-Tobias-Klein)</h4>
<pre class="lammps"><code>fix npt_mtk all npt temp 300.0 300.0 100.0 aniso 1.0 1.0 500.0</code></pre>
<p>The MTK formulation is more reliable for: - Non-equilibrium systems (with external fields) - Anisotropic stress states - Systems where pressure tensor components matter independently</p>
</section>
</section>
<section id="what-pressure-controls-physically" class="level3">
<h3 class="anchored" data-anchor-id="what-pressure-controls-physically">What Pressure Controls Physically</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 36%">
<col style="width: 36%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Pressure Change</th>
<th>Physical Effect</th>
<th>Observable</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Increase P</td>
<td>Compress system; atoms closer</td>
<td>Lower volume; higher density</td>
</tr>
<tr class="even">
<td>NPT equilibration</td>
<td>System reaches correct density</td>
<td>Density ~1 g/cm³ for water at 1 atm</td>
</tr>
<tr class="odd">
<td>Anisotropic P</td>
<td>Different stress in different directions</td>
<td>Cell angles change (for crystals)</td>
</tr>
<tr class="even">
<td>P too high</td>
<td>Over-compression; atoms too close</td>
<td>Density too high; forces too large</td>
</tr>
</tbody>
</table>
<p><strong>For water at 298 K and 1 atm</strong>: expected density ≈ 0.997 g/cm³ (SPC/E gives ~0.98 g/cm³, a known limitation).</p>
</section>
</section>
<section id="integrators-in-lammps" class="level2">
<h2 class="anchored" data-anchor-id="integrators-in-lammps">Integrators in LAMMPS</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Fix</th>
<th>Ensemble</th>
<th>Velocity Update</th>
<th>Position Update</th>
<th>Box</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>fix nve</code></td>
<td>NVE</td>
<td>Verlet</td>
<td>Verlet</td>
<td>Fixed</td>
</tr>
<tr class="even">
<td><code>fix nvt</code></td>
<td>NVT</td>
<td>Nosé-Hoover</td>
<td>Verlet</td>
<td>Fixed</td>
</tr>
<tr class="odd">
<td><code>fix npt</code></td>
<td>NPT</td>
<td>Nosé-Hoover (T) + barostat</td>
<td>Box changes</td>
<td>Changes</td>
</tr>
<tr class="even">
<td><code>fix nph</code></td>
<td>NPH</td>
<td>Barostat only</td>
<td>Box changes</td>
<td>Changes</td>
</tr>
</tbody>
</table>
<section id="combining-thermostats-and-barostats" class="level3">
<h3 class="anchored" data-anchor-id="combining-thermostats-and-barostats">Combining Thermostats and Barostats</h3>
<p><code>fix npt</code> combines both thermostat and barostat. To use them separately:</p>
<pre class="lammps"><code>fix mytemp all nvt temp 300.0 300.0 100.0    # thermostat only
fix mybar all npt temp 300.0 300.0 100.0 iso 1.0 1.0 500.0  # barostat only (and thermostat)</code></pre>
<p>Actually, <code>npt</code> already thermostats. Separate use is rare.</p>
</section>
<section id="for-electrode-simulations" class="level3">
<h3 class="anchored" data-anchor-id="for-electrode-simulations">For ELECTRODE Simulations</h3>
<p>Standard approach for static electrodes:</p>
<pre class="lammps"><code>fix frozen all nve                  # No dynamics on any atoms
fix mytemp elyte langevin 300 300 100 12345  # Only electrolyte is thermostatted</code></pre>
<p><strong>Why freeze electrodes?</strong> - Most electrode models don’t have realistic dynamics (no phonons, wrong masses) - The ELECTRODE fix computes induced charges, not forces that move atoms - Performance: fewer atoms to integrate</p>
<p><strong>If electrodes should move</strong> (charging/discharging dynamics):</p>
<pre class="lammps"><code>fix elec_nvt electrode nvt temp 300 300 100
fix elyte_nvt elyte nvt temp 300 300 100</code></pre>
<p>Or use Langevin on both:</p>
<pre class="lammps"><code>fix elec_langevin electrode langevin 300 300 100 12345
fix elyte_langevin elyte langevin 300 300 100 12345</code></pre>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Don’t Double-Thermostat
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you apply two thermostats to the same atoms, they will fight each other. Use EITHER <code>fix nvt</code> OR <code>fix langevin</code> on a given group — not both.</p>
</div>
</div>
</section>
</section>
<section id="observables-what-you-actually-measure" class="level2">
<h2 class="anchored" data-anchor-id="observables-what-you-actually-measure">Observables — What You Actually Measure</h2>
<section id="thermodynamic-output" class="level3">
<h3 class="anchored" data-anchor-id="thermodynamic-output">Thermodynamic Output</h3>
<pre class="lammps"><code>thermo 100
thermo_style custom step temp pe ke vol density</code></pre>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Physical Meaning</th>
<th>Normal Behavior</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Temp</code></td>
<td>Instantaneous temperature</td>
<td>Fluctuates ±10 K around target</td>
</tr>
<tr class="even">
<td><code>PotEng</code></td>
<td>Potential energy</td>
<td>Stable; small drift acceptable</td>
</tr>
<tr class="odd">
<td><code>KinEng</code></td>
<td>Kinetic energy</td>
<td>Fluctuates with T</td>
</tr>
<tr class="even">
<td><code>TotEng</code></td>
<td>Total energy</td>
<td>Conserved in NVE; drifts in NVT/NPT</td>
</tr>
<tr class="odd">
<td><code>Vol</code></td>
<td>System volume</td>
<td>Constant in NVT; adjusts in NPT</td>
</tr>
<tr class="even">
<td><code>Density</code></td>
<td>Mass/volume</td>
<td>Should match experimental ~1 g/cm³</td>
</tr>
<tr class="odd">
<td><code>Press</code></td>
<td>Total pressure</td>
<td>Fluctuates; mean matches external P</td>
</tr>
</tbody>
</table>
</section>
<section id="computes-for-analysis" class="level3">
<h3 class="anchored" data-anchor-id="computes-for-analysis">Computes for Analysis</h3>
<pre class="lammps"><code>compute temp_elec elyte temp     # Temperature of electrolyte only
compute stress all stress/atom  # Per-atom stress tensor (for local pressure)
compute RDF all rdf 2 * 500     # Radial distribution function g(r)
compute msd all msd            # Mean squared displacement (diffusion)</code></pre>
</section>
<section id="fix-specific-output-electrode" class="level3">
<h3 class="anchored" data-anchor-id="fix-specific-output-electrode">Fix-Specific Output (ELECTRODE)</h3>
<p>For <code>fix electrode/conp</code>, the fix stores values that can be accessed:</p>
<pre class="lammps"><code>variable Q_bot equal f_fxconp[5]    # charge on bottom electrode
variable Q_top equal f_fxconp[6]    # charge on top electrode
variable V_bot equal f_fxconp[2]   # potential on bottom (for conq mode)</code></pre>
<p>The exact indices depend on the fix configuration. To find them:</p>
<pre class="lammps"><code>print "Fix values: $(f_fxconp)"</code></pre>
</section>
<section id="trajectory-output" class="level3">
<h3 class="anchored" data-anchor-id="trajectory-output">Trajectory Output</h3>
<pre class="lammps"><code>dump 1 all custom 100 traj.lammpstrj id type x y z q
dump 2 all dcd 100 traj.dcd    # binary format; much smaller files</code></pre>
<p><strong>Post-processing tools</strong>: - <strong>Python</strong>: MDAnalysis, pytim, mdtraj, ovito-python - <strong>VMD</strong>: visualization and analysis - <strong>Ovito</strong>: visualization and statistical analysis</p>
</section>
</section>
<section id="physical-conditions-output-summary" class="level2">
<h2 class="anchored" data-anchor-id="physical-conditions-output-summary">Physical Conditions → Output Summary</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 23%">
<col style="width: 27%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th>Control Parameter</th>
<th>Physical Meaning</th>
<th>Observable in LAMMPS</th>
<th>Expected Behavior</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>T = 300 K</td>
<td>Mean kinetic energy = 3/2 k_B T</td>
<td><code>Temp</code></td>
<td>±10 K fluctuations</td>
</tr>
<tr class="even">
<td>P = 1 atm</td>
<td>External pressure</td>
<td><code>Press</code></td>
<td>Mean ≈ 1 atm, fluctuates</td>
</tr>
<tr class="odd">
<td>NVE</td>
<td>Isolated system</td>
<td><code>TotEng</code></td>
<td>&lt; 0.1% drift over 1 ns</td>
</tr>
<tr class="even">
<td>NVT</td>
<td>Canonical ensemble</td>
<td><code>Temp</code> fixed</td>
<td>Correct fluctuations</td>
</tr>
<tr class="odd">
<td>NPT</td>
<td>Isobaric</td>
<td><code>Vol</code>, <code>Density</code></td>
<td>Matches experimental density</td>
</tr>
</tbody>
</table>
</section>
<section id="common-mistakes" class="level2">
<h2 class="anchored" data-anchor-id="common-mistakes">Common Mistakes</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 38%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th>Mistake</th>
<th>Consequence</th>
<th>Correction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Thermostatting frozen atoms</td>
<td>No dynamics (atoms can’t move)</td>
<td>Only thermostat mobile atoms</td>
</tr>
<tr class="even">
<td>Using Berendsen for production</td>
<td>Wrong heat capacity</td>
<td>Use Nosé-Hoover or Langevin</td>
</tr>
<tr class="odd">
<td>Timestep too large</td>
<td>Energy drift, crash</td>
<td>Reduce Δt or constrain bonds</td>
</tr>
<tr class="even">
<td>Forgetting barostat for density</td>
<td>Wrong equilibrium density</td>
<td>Use NPT to equilibrate density</td>
</tr>
<tr class="odd">
<td>Anisotropic pressure for isotropic system</td>
<td>Stressed state, wrong density</td>
<td>Use <code>iso</code> pressure control</td>
</tr>
<tr class="even">
<td>Coupling time too small</td>
<td>Over-damped; slow equilibration</td>
<td>Use ~100 fs for NVT, ~500 fs for NPT</td>
</tr>
<tr class="odd">
<td>Double thermostatting</td>
<td>System fights itself; weird behavior</td>
<td>Check <code>fix</code> commands; only one thermostat per group</td>
</tr>
</tbody>
</table>
</section>
<section id="next-steps" class="level2">
<h2 class="anchored" data-anchor-id="next-steps">Next Steps</h2>
<ul>
<li><strong>?@sec-electrostatics</strong> — How long-range electrostatics is handled</li>
<li><strong>?@sec-electrodes-cpm</strong> — Why electrodes need constant potential (not constant charge)</li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/srtee\.github\.io\/mddocs\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>