project:
  type: website

website:
  title: "Shern's Molecular Dynamics Docs"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
        href: introduction.qmd
      - section: "Basics"
        contents:
          - "getting-started.qmd"
          - "time-and-length-scales.qmd"
          - "integrators.qmd"
          - "forces.qmd"
          - "thermostats.qmd"
          - "barostats.qmd"
      - section: "My Research Areas"
        contents:
          - "constant-potential-I.qmd"
          - "constant-potential-II.qmd"
          - "electrolytes.qmd"
          - "quartic-constraints.qmd"
          - "research-software-engineering.qmd"
          - "SoTL.qmd"
      - section: "Using LAMMPS"
        contents:
          - "lammps-basics.qmd"
          - "input-scripts.qmd"
          - "force-fields.qmd"
          - "output-files.qmd"
          - "folder-practices.qmd"
      - section: "Using VMD"
        contents:
          - "loading-data.qmd"
          - "pbc-adjustments.qmd"
      - "acknowledgment.qmd"

format:
  html:
    theme: cosmo
    toc: true
    #css: styles.css